name: 🏗️ Feature
description: Feature request
title: "[FEATURE]"
labels: [improvement]
body:
- type: checkboxes
  attributes:
    label: Is there an existing issue for this?
    description: Please search to see if an issue already exists for the feature request.
    options:
    - label: I have searched the existing issues
      required: true
- type: textarea
  attributes:
    label: Issue / Request Related to a Problem?
    description: A clear and concise description of what the problem is.
    placeholder: ex. I'm always frustrated when [...].
  validations:
    required: false
- type: textarea
  attributes:
    label: Solution
    description: Sequence of steps needed to complete this feature.
    value: |
      - [ ] Step 1
      - [ ] Step 2
      - [ ] Step 3
  validations:
    required: false
- type: textarea
  attributes:
    label: Designs & Markups
    description: Provide any designs and/or wire frames
  validations:
    required: false
- type: textarea
  attributes:
    label: External Resources
    description: Links to external resources
  validations:
    required: false
- type: textarea
  attributes:
    label: Additional Context
    description: Add any other context or screenshots about the feature request here.
  validations:
    required: false
- type: checkboxes
  id: terms
  attributes:
    label: Code of Conduct
    description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
    options:
      - label: I agree to follow this project's Code of Conduct
        required: true
