name: 'Auto Update PR'

on:
  push:
      branches:
      - '*'
      - '!staging'
      - '!production'

jobs:
  autoupdate:
    name: ✨ Auto Update
    runs-on: ubuntu-20.04
    steps:
      - uses: docker://chinthakagodawita/autoupdate-action:v1
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          DRY_RUN: "false"
          PR_FILTER: "labelled"
          PR_LABELS: "autoupdate,keep up-to-date"
          EXCLUDED_LABELS: "dependencies,wontfix,wip"
          MERGE_MSG: "Branch was auto-updated."
          RETRY_COUNT: "5"
          RETRY_SLEEP: "300"
          MERGE_CONFLICT_ACTION: "fail"
